package net.uselesscode.yuruweb202210.domain;

/**
 * Database Table Remarks:
 *   å†å¿É}ÉXÉ^
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.role_master
 */
public class RoleMaster {

	/**
	 * Database Column Remarks: å†å¿ID This field was generated by MyBatis Generator. This field corresponds to the database column public.role_master.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: å†å¿ñº This field was generated by MyBatis Generator. This field corresponds to the database column public.role_master.name
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_master.id
	 * @return  the value of public.role_master.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_master.id
	 * @param id  the value for public.role_master.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.role_master.name
	 * @return  the value of public.role_master.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.role_master.name
	 * @param name  the value for public.role_master.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}