package net.uselesscode.yuruweb202210.domain;

/**
 * Database Table Remarks:
 *   ユーザーマスタ
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.user_master
 */
public class UserMaster {

	/**
	 * Database Column Remarks: ユーザーID This field was generated by MyBatis Generator. This field corresponds to the database column public.user_master.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: ユーザー名 This field was generated by MyBatis Generator. This field corresponds to the database column public.user_master.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: メールアドレス This field was generated by MyBatis Generator. This field corresponds to the database column public.user_master.mail
	 * @mbg.generated
	 */
	private String mail;
	/**
	 * Database Column Remarks: パスワード This field was generated by MyBatis Generator. This field corresponds to the database column public.user_master.password
	 * @mbg.generated
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_master.id
	 * @return  the value of public.user_master.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_master.id
	 * @param id  the value for public.user_master.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_master.name
	 * @return  the value of public.user_master.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_master.name
	 * @param name  the value for public.user_master.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_master.mail
	 * @return  the value of public.user_master.mail
	 * @mbg.generated
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_master.mail
	 * @param mail  the value for public.user_master.mail
	 * @mbg.generated
	 */
	public void setMail(String mail) {
		this.mail = mail == null ? null : mail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_master.password
	 * @return  the value of public.user_master.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_master.password
	 * @param password  the value for public.user_master.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
}