package net.uselesscode.yuruweb202210.domain;

/**
 * Database Table Remarks:
 *   ユーザー権限マスタ
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.user_role_master
 */
public class UserRoleMasterKey {

	/**
	 * Database Column Remarks: ユーザーID This field was generated by MyBatis Generator. This field corresponds to the database column public.user_role_master.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 権限ID This field was generated by MyBatis Generator. This field corresponds to the database column public.user_role_master.role_id
	 * @mbg.generated
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_role_master.user_id
	 * @return  the value of public.user_role_master.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_role_master.user_id
	 * @param userId  the value for public.user_role_master.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.user_role_master.role_id
	 * @return  the value of public.user_role_master.role_id
	 * @mbg.generated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.user_role_master.role_id
	 * @param roleId  the value for public.user_role_master.role_id
	 * @mbg.generated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}