package net.uselesscode.yuruweb202210.mapper;

import java.util.List;
import net.uselesscode.yuruweb202210.domain.RoleMaster;
import net.uselesscode.yuruweb202210.domain.RoleMasterExample;
import org.apache.ibatis.annotations.Param;

public interface RoleMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	long countByExample(RoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int deleteByExample(RoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int insert(RoleMaster row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int insertSelective(RoleMaster row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	List<RoleMaster> selectByExample(RoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	RoleMaster selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") RoleMaster row, @Param("example") RoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") RoleMaster row, @Param("example") RoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RoleMaster row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.role_master
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RoleMaster row);
}