package net.uselesscode.yuruweb202210.mapper;

import java.util.List;
import net.uselesscode.yuruweb202210.domain.UserRoleMasterExample;
import net.uselesscode.yuruweb202210.domain.UserRoleMasterKey;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	long countByExample(UserRoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int deleteByExample(UserRoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(UserRoleMasterKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int insert(UserRoleMasterKey row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int insertSelective(UserRoleMasterKey row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	List<UserRoleMasterKey> selectByExample(UserRoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") UserRoleMasterKey row, @Param("example") UserRoleMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.user_role_master
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") UserRoleMasterKey row, @Param("example") UserRoleMasterExample example);
}